name: Docker Image CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
env:
  APP_NAME: kvibe-ws

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build jar
        if: success() # only runs if all tests pass
        run: ./gradlew bootJar # mvn package work just fine for maven
    
      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: |
            ghcr.io/e-citaonica/${{ env.APP_NAME }}
          tags: |
            type=raw,value=1.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: kvibe-ws/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
